---
title: "App1"
author: "Villaseñor-Derbez, J.C."
date: "1 de marzo de 2016"
output: ioslides_presentation
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(MPA.tools)
```

## Equation

The model is:


## App

```{r turf-reserves, echo=FALSE}
inputPanel(
  selectInput("nsteps", label = "Number of steps:",
              choices = c(10, 20, 30, 40), selected = 20),
  
  sliderInput("urate", label = "Harvesting rate:",
              min = 0, max = 1, value = 0.4, step = 0.1)
)

renderPlot({
  area=matrix(input$urate,nrow=50, ncol=50)
  #SINGLE LARGE
  area1=area
  area1[23:27,23:27]=0
  
  data=mpa_sim(r=0.2, pop0=1000, K=1000, area=area1, nsteps=input$nsteps, mrate=0.4, op=FALSE)
  
  #SEVERAL SMALL
area4=area
area4[13:37,25]=0
for (i in 1:24){
  area4[,24-i]=input$urate/i
  area4[,26+i]=input$urate/i
}

area4[1:11,21:29]=t(area4[21:29,12:22])
area4[39:50,21:29]=t(area4[21:29,28:39])

data2=mpa_sim(r=0.2, pop0=1000, K=1000, area=area4, nsteps=input$nsteps, mrate=0.4, op=FALSE)

  plot(data2$time.series$time, data2$time.series$pop.in, type="b", col="red", ylim=c(0,1000))
  lines(data$time.series$time, data$time.series$pop.in, type="b", col="blue")
})

```

