#' Fix NA
#'
#' @description Removes all na-variables (see value) to avoid errors when performing the linear model
#'
#' @param data a data.frame, generated by any of the MPAtools::indicator functions
#'
#' @return a data.frame where all-na variables (i.e. the entire column had NA) are replaced with a 1
#' @export
#'

fix_na <- function(data){

  data_length <- dim(data)[1]

  naT <- sum(is.na(data$Temperatura))
  naP <- sum(is.na(data$Visibilidad))
  naV <- sum(is.na(data$Profundidad))

  if(naT == data_length){data$Temperatura <- 1}
  if(naP == data_length){data$Visibilidad <- 1}
  if(naV == data_length){data$Profundidad <- 1}

  return(data)
}
