#' Plots results from biophysical indicator functions
#'
#' @description Plots results from the functions used to calculate biophysical indicators like: richness(), density(), ttrophic(), fish_biomass(), and fish_size().
#'
#' @param data dataframe generated by any of the following functions: richness(), density(), trophic(), fish_biomass(), and fish_size()
#'
#' @param type a quoted character that indicates which function was used to create the data frame. Use "s", "d", "t", "b", and "l", respectively.
#'
#' @export
#'
#' @author Villasenor-Derbez, J.C.

mpa_plot2 <- function(data, type){

  ## QUitar los stat_summary e incluir cachito de dplyr para que agrupe por zona

  library(ggplot2)
  library(dplyr)
  library(tidyr)

  if (type == "s"){
    data <- data %>%
      group_by(Ano, Zonificacion) %>%
      mutate(S = mean(S, na.rm = T))

    p <- ggplot(data, aes(x = Ano, y = S, color = Zonificacion))+
      geom_point()+
      stat_summary(fun.y = "mean", geom = "line")+
      theme_bw()+
      scale_color_brewer(palette = "Set1")
  }
  if (type == "d"){
    data <- data %>%
      group_by(Ano, Zonificacion) %>%
      mutate(D = mean(D, na.rm = T))

    p <- ggplot(data, aes(x = Ano, y = D, color = Zonificacion))+
      geom_point()+
      stat_summary(fun.y = "mean", geom = "line")+
      theme_bw()+
      scale_color_brewer(palette = "Set1")
  }
  if (type == "t"){
    data <- data %>%
      group_by(Ano, Zonificacion) %>%
      mutate(mean = mean(mean))

    p <- ggplot(data, aes(x = Ano, y = mean, color = Zonificacion))+
      geom_point()+
      stat_summary(fun.y = "mean", geom = "line")+
      theme_bw()+
      scale_color_brewer(palette = "Set1")
  }
  if (type == "b"){
    data <- data %>%
      group_by(Ano, Zonificacion) %>%
      mutate(B = mean(B))

    p <- ggplot(data, aes(x = Ano, y = B, color = Zonificacion))+
      geom_point()+
      stat_summary(fun.y = "mean", geom = "line")+
      theme_bw()+
      scale_color_brewer(palette = "Set1")
  }
  if (type == "l"){
    data <- data %>%
      group_by(Ano, Zonificacion) %>%
      mutate(stat = mean (stat))

    p <- ggplot(data, aes(x = Ano, y = stat, color = Zonificacion))+
      geom_point()+
      stat_summary(fun.y = "mean", geom = "line")+
      theme_bw()+
      scale_color_brewer(palette = "Set1")
  }

  p
}
