#' Title
#'
#' @param model An object of class lm, generated by the turfeffect() function or extracted from the tibble output of the bio_results() function
#'
#' @return an object og class ggplot2
#' @export
#'

mpa_plot4 <- function(model, y.lab = NULL) {

  p <- model$model %>%
    ggplot(aes(x = Ano, y = Indicador, color = Zona, fill = Zona)) +
    geom_jitter(width = 0.1, size = 1) +
    stat_summary(geom = "point", fun.y = mean, color = "black", size = 2, alpha = 0.5) +
    stat_summary(geom = "line", fun.y = mean, color = "black", alpha = 0.5) +
    stat_summary(fun.data = mean_se, geom = "ribbon", alpha = 0.5) +
    scale_color_brewer(palette = "Set1") +
    scale_fill_brewer(palette = "Set1") +
    theme_bw() + labs(x = "Ano", y = y.lab)

  return(p)
}
