#' Plots results from biophysical indicator functions
#'
#' @description Plots results from the functions used to calculate biophysical indicators like: richness(), density(), ttrophic(), fish_biomass(), and fish_size().
#'
#' @param data dataframe generated by any of the following functions: richness(), density(), trophic(), fish_biomass(), and fish_size()
#'
#' @param type a quoted character that indicates which function was used to create the data frame. Use "s", "d", "t", "b", and "l", respectively.
#'
#' @export
#'
#' @author Villasenor-Derbez, J.C.

mpa_plot2=function(data, type){
  if (type=="s"){
    ggplot(data, aes(x=Year, y=S, color=Zone))+
      geom_point()+
      stat_summary(fun.y="mean", geom="line")+
      theme_bw()+
      scale_color_brewer(palette="Set1")
  }

  if (type=="d"){
    ggplot(data, aes(x=Year, y=D, color=Zone, factor=GeneroEspecie))+
      geom_point()+
      stat_summary(fun.y="mean", geom="line")+
      theme_bw()+
      scale_color_brewer(palette="Set1")
  }

  if (type=="t"){
    ggplot(data, aes(x=Year, y=mean, color=Zone))+
      geom_point()+
      stat_summary(fun.y="mean", geom="line")+
      theme_bw()+
      scale_color_brewer(palette="Set1")
  }

  if (type=="b"){
    ggplot(data, aes(x=Year, y=B, color=Zone))+
      geom_point()+
      stat_summary(fun.y="mean", geom="line")+
      theme_bw()+
      scale_color_brewer(palette="Set1")
  }

  if (type=="l"){
    ggplot(data, aes(x=Year, y=stat, color=Zone))+
      geom_point()+
      stat_summary(fun.y="mean", geom="line")+
      theme_bw()+
      scale_color_brewer(palette="Set1")
  }
}
