#' Plots results from biophysical indicator functions
#'
#' @description Plots results from the functions used to calculate biophysical indicators like: richness(), density(), ttrophic(), fish_biomass(), and fish_size().
#'
#' @param data dataframe generated by any of the following functions: richness(), density(), trophic(), fish_biomass(), and fish_size()
#'
#' @param error.bars A logical value indicating if error bars (1 SD) should be plotted.
#'
#' @export
#'
#' @author Villasenor-Derbez, J.C.

mpa_plot2 <- function(data, error.bars = F){

  library(ggplot2)
  library(dplyr)
  library(tidyr)

  data <- data %>%
    group_by(Ano, Zonificacion) %>%
    mutate(SD = sd(S, na.rm = T), Indicator = mean(S, na.rm = T))

  p <- ggplot(data, aes(x = Ano, y = Indicator, color = Zonificacion))+
    geom_point()+
    geom_line()+
    theme_bw()+
    scale_color_brewer(palette = "Set1")

  if (error.bars){
    p <- p +
      geom_errorbar(aes(ymin = Indicator-SD, ymax = Indicator+SD), width = 0.2)
  }


  p
}
