#' Title
#'
#' @param model a linear model generated by the turfeffect function
#'
#' @return score
#' @export
#'

soc_score <- function(model) {

  est = model$estimate
  p = model$p

  if (est > 0 & p < 0.05) {
    score = "olive"
  }

  if (est > 0 & p > 0.05) {
    score = "green"
  }

  if (est == 0) {
    score = "yellow"
  }

  if (est < 0 & p > 0.05) {
    score = "orange"
  }

  if (est < 0 & p < 0.05) {
    score = "red"
  }

  return(score)

}
