#' Plot a turfeffect object for socioeconomic indicators
#'
#' @param model An object of class lm, generated by the turfeffect() function or extracted from the tibble output of the bio_results() function
#' @param y.lab A character that specifies the y label
#'
#' @return an object og class ggplot2
#' @export
#'

soc_plot <- function(model, y.lab){
  library(ggplot2)
  library(dplyr)
  library(tidyr)

  p <- model$model %>%
    ggplot(aes(x = Ano, y = Indicador)) +
    stat_summary(geom = "point", fun.y = mean, color = "black", size = 2) +
    stat_summary(geom = "line", fun.y = mean, color = "black") +
    theme_bw() +
    labs(x = "Ano", y = y.lab)

  return(p)
}
