#' turfeffect
#'
#' @param data A data.frame generated by any of the following functions: richness(), density(), trophic(), fish_biomass(), and fish_size().
#' @param reserve A string
#' @param control A string
#'
#' @return An object of class "lm"
#'
#' @export

turfeffect <- function (data, reserve, control){

  library(dplyr)
  library(tidyr)

  columnas <- c("Ano", "Zonificacion", "Sitio", "Transecto", "Indicador", "Temperatura", "Visibilidad", "Profundidad")

  colnames(data) <- columnas

  data <- filter(data, Sitio == reserve | Sitio == control)

  dummy.data <- data.frame(Ano = data$Ano,
                           Zona = NA,
                           Sitio = data$Sitio,
                           Indicador = data$Indicador,
                           Temperatura = data$Temperatura,
                           Profundidad = data$Profundidad,
                           Visibilidad = data$Visibilidad)

  dummy.data$Zona[data$Zonificacion == "Reserva"] <- 0
  dummy.data$Zona[data$Zonificacion == "Control"] <- 1

  model <- lm(Indicador ~ Ano * Zona + Temperatura + Visibilidad + Profundidad, data = dummy.data)

  return(model)
}
