#' turfeffect
#'
#' @param data A data.frame generated by any of the following functions: richness(), density(), trophic(), fish_biomass(), and fish_size().
#' @param reserve A string
#' @param control A string
#' @param type A string
#'
#' @return An object of class "lm"
#'
#' @export

turfeffect <- function (data, reserve = NULL, control = NULL, type = NULL, year.imp = NULL){

  library(tidyverse)

  data <- data %>%
    mutate(Post = as.factor(ifelse(Ano <= year.imp, 0, 1)),
           Ano = as.factor(Ano))

    colnames(data) <- c("Ano", "Zona", "Sitio", "Transecto", "Indicador", "Temperatura", "Visibilidad", "Profundidad")

    data <- filter(data, Sitio %in% reserve | Sitio %in% control) %>%
      mutate(Post = ifelse(Ano <= min(Ano), 0, 1)) %>%
      fix_na()

    model <- lm(Indicador ~ Ano + Zona+ Post * Zona + Temperatura + Visibilidad + Profundidad, data)

  } else if (type == "soc"){

    colnames(data) <- c("Ano", "Indicador")

    model <- lm(Indicador ~ Ano, data = data)
  }

  return(model)
}
