#' turfeffect
#'
#' @param data A data.frame generated by any of the following functions: richness(), density(), trophic(), fish_biomass(), and fish_size().
#' @param reserve A string
#' @param control A string
#'
#' @return An object of class "lm"
#'
#' @export

turfeffect <- function (data, reserve = NULL, control = NULL, type = NULL){

  library(tidyverse)

  if (type == "bio"){

    colnames(data) <- c("Ano", "Zona", "Sitio", "Transecto", "Indicador", "Temperatura", "Visibilidad", "Profundidad")

      data <- filter(data, Sitio == reserve | Sitio == control)

      model <- lm(Indicador ~ Ano * Zona + Temperatura + Visibilidad + Profundidad, data)

  } else if (type == "soc"){

    colnames(data) <- c("Ano", "Indicador")

      model <- lm(Indicador ~ Ano, data = data)
  }

  return(model)
}
